export const SET_USER_SIGN_UP ='SET_USER_SIGN_UP'
export const SET_USER_SIGN_IN ='SET_USER_SIGN_IN'
export const SET_TOKEN_CONFIRM ='SET_TOKEN_CONFIRM'
export const SET_ERRORS_MESSAGE ='SET_ERRORS_MESSAGE'